server:
  port: 8084

spring:
  application:
    name: users-microservice
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,templates/**
    livereload:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
