spring.application.name=api-gateway
server.port=8083

spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates=Path=/users/**

spring.cloud.gateway.routes[1].id=tasks-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates=Path=/tasks/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG

